language: python
dist: xenial

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO=2.2
  - python: "2.7"
    env: DJANGO=3.0
  - python: "3.7"
    env: DJANGO=1.11

install:
  - pip install Django==$DJANGO
  - pip install coveralls
  - pip install -e .

script:
  - coverage run --source=webshell setup.py test

after_success:
  - coveralls
